WebGL/WebGL/Controllers/PersonnesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WcfGL.Models;
using PagedList.Mvc;
using PagedList;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace WebGL.Controllers
{
    public class PersonnesController : Controller
    {
        //private BdWebGlContext db = new BdWebGlContext();
        private WcfGLs.Service1Client service = new WcfGLs.Service1Client();
        int pageSize = 3;

        // GET: Personnes
        public ActionResult Index(string TelPersonne, string DateNaissancePersonne, int? page)
        {
            page = page.HasValue ? page : 1;
            ViewBag.TelPersonne = !string.IsNullOrEmpty(TelPersonne) ? TelPersonne : string.Empty;
            ViewBag.DateNaissancePersonne = !string.IsNullOrEmpty(DateNaissancePersonne) ? DateNaissancePersonne : string.Empty;
            return View(service.GetPersonnes(TelPersonne, DateNaissancePersonne).ToPagedList((int)page, pageSize));
            //return View(GetAllPersonneAPI().ToPagedList((int)page, pageSize));
            //return View(GetAllPersonneApiPHP().ToPagedList((int)page, pageSize));
        }

        // GET: Personnes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personne personne = service.GetPersonneByID((int)id);
            //Personne personne = GetPersonneByIdAPI((int)id);
            //Personne personne = GetPersonneByIdAPIPHP((int)id);
            if (personne == null)
            {
                return HttpNotFound();
            }
            return View(personne);
        }

        // GET: Personnes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Personnes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPersonne,NomPrenomPersonne,AdressePersonne,TelPersonne,EmailPersonne,DateNaissancePersonne")] Personne personne)
        {
            if (ModelState.IsValid)
            {
                service.AddPersonne(personne);
                //AddPersonneAPI(personne);
                //AddPersonneAPIPHP(personne);
                return RedirectToAction("Index");
            }

            return View(personne);
        }

        // GET: Personnes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personne personne = service.GetPersonneByID((int)id);
            //Personne personne = GetPersonneByIdAPI((int)id);
            //Personne personne = GetPersonneByIdAPIPHP((int)id);
            if (personne == null)
            {
                return HttpNotFound();
            }
            return View(personne);
        }

        // POST: Personnes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPersonne,NomPrenomPersonne,AdressePersonne,TelPersonne,EmailPersonne,DateNaissancePersonne")] Personne personne)
        {
            if (ModelState.IsValid)
            {
                service.UpdatePersonne(personne);
                //UpdatePersonneAPI(personne);
                //UpdatePersonneAPIPHP(personne);
                return RedirectToAction("Index");
            }
            return View(personne);
        }

        // GET: Personnes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personne personne = service.GetPersonneByID((int)id);
            //Personne personne = GetPersonneByIdAPI((int)id);
            //Personne personne = GetPersonneByIdAPIPHP((int)id);
            if (personne == null)
            {
                return HttpNotFound();
            }
            return View(personne);
        }

        // POST: Personnes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            service.DeletePersonne((int)id);
            //DeletePersonneAPI((int)id);
            //DeletePersonneAPIPHP();
            return RedirectToAction("Index");
        }


        /*
         *Ecriture des fonctioncs 
         * Permettant la 
         * consomma de l'API  WEBAPIGL 
         */


        public List<Personne> GetAllPersonneAPI()
        {
            HttpClient client;
            client = new HttpClient();
            var personnes = new List<Personne>();
            client.BaseAddress = new Uri(System.Configuration.ConfigurationManager.AppSettings["ServeurApiURL"]);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = client.GetAsync("api/personnes/GetAllPersonnes").Result;

            if (response.IsSuccessStatusCode)
            {
                var responseData = response.Content.ReadAsStringAsync().Result;
                personnes = JsonConvert.DeserializeObject<List<Personne>>(responseData);
            }
            return personnes;
        }

        public Personne GetPersonneByIdAPI(int id)
        {
            HttpClient client;
            client = new HttpClient();
            var personne = new Personne();
            client.BaseAddress = new Uri(System.Configuration.ConfigurationManager.AppSettings["ServeurApiURL"]);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = client.GetAsync("api/personnes/GetPersonneById/"+id).Result;

            if (response.IsSuccessStatusCode)
            {
                var responseData = response.Content.ReadAsStringAsync().Result;
                personne = JsonConvert.DeserializeObject<Personne>(responseData);
            }
            return personne;
        }

        public bool AddPersonneAPI(Personne personne)
        {
            bool rep = false;
            string idpersonne = personne.IdPersonne > 0 ? personne.IdPersonne.ToString() : string.Empty;
            var values = new Dictionary<string, string>
                    {
                        { "IdPersonne", idpersonne },
                        { "NomPrenomPersonne", personne.NomPrenomPersonne },
                        { "AdressePersonne", personne.AdressePersonne },
                        { "TelPersonne", personne.TelPersonne },
                        { "EmailPersonne", personne.EmailPersonne },
                        { "DateNaissancePersonne", personne.DateNaissancePersonne.ToString() }
                    };
            var content = new FormUrlEncodedContent(values);
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(System.Configuration.ConfigurationManager.AppSettings["ServeurApiURL"]);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = client.PostAsync("api/personnes/AddPersonne", content).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        rep = true;
                    }
                    else
                    {

                    }

                }
            }
            catch (Exception ex)
            {

            }
            return rep;
        }
        public bool UpdatePersonneAPI(Personne personne)
        {
            bool rep = false;
            var values = new Dictionary<string, string>
                    {
                        { "IdPersonne", personne.IdPersonne.ToString() },
                        { "NomPrenomPersonne", personne.NomPrenomPersonne },
                        { "AdressePersonne", personne.AdressePersonne },
                        { "TelPersonne", personne.TelPersonne },
                        { "EmailPersonne", personne.EmailPersonne },
                        { "DateNaissancePersonne", personne.DateNaissancePersonne.ToString() }
                    };
            var content = new FormUrlEncodedContent(values);
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(System.Configuration.ConfigurationManager.AppSettings["ServeurApiURL"]);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = client.PutAsync("api/personnes/UpdatePersonne/" + personne.IdPersonne, content).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        rep = true;
                    }
                    else
                    {

                    }

                }
            }
            catch (Exception ex)
            {

            }
            return rep;
        }

WebGL/WebGL/Views/Personnes/Create.cshtml
@model WcfGL.Models.Personne

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personne</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomPrenomPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomPrenomPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomPrenomPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdressePersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdressePersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdressePersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateNaissancePersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissancePersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissancePersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebGL/WebGL/Views/Personnes/Delete.cshtml
@model WcfGL.Models.Personne

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Personne</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomPrenomPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomPrenomPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressePersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressePersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissancePersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissancePersonne)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebGL/WebGL/Views/Personnes/Details.cshtml
@model WcfGL.Models.Personne

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Personne</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomPrenomPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomPrenomPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressePersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressePersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailPersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailPersonne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissancePersonne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissancePersonne)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPersonne }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebGL/WebGL/Views/Personnes/Edit.cshtml
@model WcfGL.Models.Personne

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personne</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPersonne)

        <div class="form-group">
            @Html.LabelFor(model => model.NomPrenomPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomPrenomPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomPrenomPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdressePersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdressePersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdressePersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailPersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailPersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailPersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateNaissancePersonne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissancePersonne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissancePersonne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebGL/WebGL/Views/Personnes/Index.cshtml
@model PagedList.IPagedList<WcfGL.Models.Personne>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<br />
<div class="row">
    <div class="col-xs-12 col-md-12">
        <div class="widget">


            <div class="widget-body">

                @using (Html.BeginForm("Index", "Personnes", FormMethod.Get))
                {
                    <div class="row">

                        <div class="col-md-2">
                            <div class="form-group">
                                <b> Téléphone</b>
                                @Html.TextBox("TelPersonne", ViewBag.TelPersonne as string, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <b> Date de Naissance</b>
                                @Html.TextBox("DateNaissancePersonne", ViewBag.DateNaissancePersonne as string, new { @class = "form-control" })
                            </div>
                        </div>

                    </div>
                    <div><input type="submit" value="Rechercher" class="btn btn-primary" /></div>

                }

            </div>


        </div>

    </div>
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().NomPrenomPersonne)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AdressePersonne)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TelPersonne)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().EmailPersonne)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().DateNaissancePersonne)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomPrenomPersonne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdressePersonne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelPersonne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailPersonne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateNaissancePersonne)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdPersonne }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdPersonne }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdPersonne })
            </td>
        </tr>
    }

</table>
<br />
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, TelPersonne = @ViewBag.TelPersonne, DateNaissancePersonne = @ViewBag.DateNaissancePersonne, }))